# Generated by Django 5.2.6 on 2025-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('submitted', 'Submitted')], default='applied', max_length=100)),
                ('resume_text', models.TextField(blank=True)),
                ('date_applied', models.DateTimeField()),
            ],
        ),
    ]
